home:
  alias: '/basics'

pages:
  theme: learn
  markdown_extra: true
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    method: folder
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: true
  css_minify: true
  css_rewrite: true
  js_pipeline: true
  js_minify: true

debugger:
  enabled: false
  twig: false
  shutdown:
    close_connection: true
errors:
  display: false
  log: true
